// Auto-generated by `clank init`. Fires `clank push` when an opencode
// session goes idle, mirroring the worktree's code + sessions to your
// active clank remote. Overwritten on the next `clank init`.
const CLANK_BIN = __CLANK_BIN__

export const ClankAutoPush = async ({ $, directory, worktree }) => {
  return {
    event: async ({ event }) => {
      if (event?.type !== "session.idle") return
      const cwd = worktree || directory
      if (!cwd) return
      try {
        await $`${CLANK_BIN} push ${cwd}`.quiet().nothrow()
      } catch {}
    },
  }
}
