// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package hostsqlitedb

import (
	"database/sql"
	"time"
)

type PrimaryAgent struct {
	Backend           string
	ProjectDir        string
	WorktreeID        string
	PrimaryAgentsJson string
	UpdatedAt         time.Time
}

type Session struct {
	ID             string
	ExternalID     string
	Backend        string
	Status         string
	Visibility     string
	FollowUp       int64
	ProjectDir     string
	WorktreeID     string
	WorktreeBranch string
	Prompt         string
	Title          string
	TicketID       string
	Agent          string
	Draft          string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	LastReadAt     sql.NullTime
}
