// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package hostsqlitedb

import (
	"context"
)

type Querier interface {
	DeleteSession(ctx context.Context, id string) error
	// Removes every session belonging to a worktree. Used when a worktree is
	// deleted (full cleanup), alongside removing its materialized ~/work/<id>.
	DeleteSessionsByWorktree(ctx context.Context, worktreeID string) error
	FindSessionByExternalID(ctx context.Context, externalID string) (Session, error)
	GetSession(ctx context.Context, id string) (Session, error)
	ListPrimaryAgents(ctx context.Context, arg ListPrimaryAgentsParams) (string, error)
	ListSessions(ctx context.Context) ([]Session, error)
	// Used by session-sync to enumerate sessions in a worktree for export.
	// worktree_id is the host-minted worktree ULID; cross-machine stable identity.
	ListSessionsByWorktree(ctx context.Context, worktreeID string) ([]Session, error)
	// Filtered list. Empty filter values are treated as "no filter" by
	// the query (NULL/empty matches anything for that column). Visibility
	// filter is exact match.
	SearchSessions(ctx context.Context, arg SearchSessionsParams) ([]Session, error)
	UpsertPrimaryAgents(ctx context.Context, arg UpsertPrimaryAgentsParams) error
	UpsertSession(ctx context.Context, arg UpsertSessionParams) error
}

var _ Querier = (*Queries)(nil)
