// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package hostsqlitedb

import (
	"context"
)

type Querier interface {
	DeleteSession(ctx context.Context, id string) error
	FindSessionByExternalID(ctx context.Context, externalID string) (Session, error)
	GetSession(ctx context.Context, id string) (Session, error)
	ListPrimaryAgents(ctx context.Context, arg ListPrimaryAgentsParams) (string, error)
	ListSessions(ctx context.Context) ([]Session, error)
	// Filtered list. Empty filter values are treated as "no filter" by
	// the query (NULL/empty matches anything for that column). Visibility
	// filter is exact match.
	SearchSessions(ctx context.Context, arg SearchSessionsParams) ([]Session, error)
	UpsertPrimaryAgents(ctx context.Context, arg UpsertPrimaryAgentsParams) error
	UpsertSession(ctx context.Context, arg UpsertSessionParams) error
}

var _ Querier = (*Queries)(nil)
