// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package hostsqlitedb

import (
	"context"
	"database/sql"
	"time"
)

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const findSessionByExternalID = `-- name: FindSessionByExternalID :one
SELECT id, external_id, backend, status, visibility, follow_up, project_dir, git_remote, worktree_branch, prompt, title, ticket_id, agent, draft, created_at, updated_at, last_read_at FROM sessions WHERE external_id = ? LIMIT 1
`

func (q *Queries) FindSessionByExternalID(ctx context.Context, externalID string) (Session, error) {
	row := q.db.QueryRowContext(ctx, findSessionByExternalID, externalID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Backend,
		&i.Status,
		&i.Visibility,
		&i.FollowUp,
		&i.ProjectDir,
		&i.GitRemote,
		&i.WorktreeBranch,
		&i.Prompt,
		&i.Title,
		&i.TicketID,
		&i.Agent,
		&i.Draft,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastReadAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, external_id, backend, status, visibility, follow_up, project_dir, git_remote, worktree_branch, prompt, title, ticket_id, agent, draft, created_at, updated_at, last_read_at FROM sessions WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Backend,
		&i.Status,
		&i.Visibility,
		&i.FollowUp,
		&i.ProjectDir,
		&i.GitRemote,
		&i.WorktreeBranch,
		&i.Prompt,
		&i.Title,
		&i.TicketID,
		&i.Agent,
		&i.Draft,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastReadAt,
	)
	return i, err
}

const listPrimaryAgents = `-- name: ListPrimaryAgents :one
SELECT primary_agents_json FROM primary_agents
WHERE backend = ? AND project_dir = ? AND git_remote = ?
`

type ListPrimaryAgentsParams struct {
	Backend    string
	ProjectDir string
	GitRemote  string
}

func (q *Queries) ListPrimaryAgents(ctx context.Context, arg ListPrimaryAgentsParams) (string, error) {
	row := q.db.QueryRowContext(ctx, listPrimaryAgents, arg.Backend, arg.ProjectDir, arg.GitRemote)
	var primary_agents_json string
	err := row.Scan(&primary_agents_json)
	return primary_agents_json, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, external_id, backend, status, visibility, follow_up, project_dir, git_remote, worktree_branch, prompt, title, ticket_id, agent, draft, created_at, updated_at, last_read_at FROM sessions ORDER BY updated_at DESC
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Backend,
			&i.Status,
			&i.Visibility,
			&i.FollowUp,
			&i.ProjectDir,
			&i.GitRemote,
			&i.WorktreeBranch,
			&i.Prompt,
			&i.Title,
			&i.TicketID,
			&i.Agent,
			&i.Draft,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSessions = `-- name: SearchSessions :many
SELECT id, external_id, backend, status, visibility, follow_up, project_dir, git_remote, worktree_branch, prompt, title, ticket_id, agent, draft, created_at, updated_at, last_read_at FROM sessions
WHERE
    (CAST(?1 AS TEXT) = '' OR title LIKE '%' || ?1 || '%' OR prompt LIKE '%' || ?1 || '%' OR draft LIKE '%' || ?1 || '%' OR project_dir LIKE '%' || ?1 || '%')
    AND (CAST(?2 AS TEXT) = '' OR visibility = ?2)
    AND (?3 IS NULL OR updated_at >= ?3)
    AND (?4 IS NULL OR updated_at <= ?4)
ORDER BY updated_at DESC
LIMIT ?5
`

type SearchSessionsParams struct {
	Q          string
	Visibility string
	Since      interface{}
	Until      interface{}
	Lim        int64
}

// Filtered list. Empty filter values are treated as "no filter" by
// the query (NULL/empty matches anything for that column). Visibility
// filter is exact match.
func (q *Queries) SearchSessions(ctx context.Context, arg SearchSessionsParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, searchSessions,
		arg.Q,
		arg.Visibility,
		arg.Since,
		arg.Until,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Backend,
			&i.Status,
			&i.Visibility,
			&i.FollowUp,
			&i.ProjectDir,
			&i.GitRemote,
			&i.WorktreeBranch,
			&i.Prompt,
			&i.Title,
			&i.TicketID,
			&i.Agent,
			&i.Draft,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPrimaryAgents = `-- name: UpsertPrimaryAgents :exec
INSERT INTO primary_agents (
    backend, project_dir, git_remote, primary_agents_json, updated_at
) VALUES (?, ?, ?, ?, ?)
ON CONFLICT (backend, project_dir, git_remote) DO UPDATE SET
    primary_agents_json = excluded.primary_agents_json,
    updated_at          = excluded.updated_at
`

type UpsertPrimaryAgentsParams struct {
	Backend           string
	ProjectDir        string
	GitRemote         string
	PrimaryAgentsJson string
	UpdatedAt         time.Time
}

func (q *Queries) UpsertPrimaryAgents(ctx context.Context, arg UpsertPrimaryAgentsParams) error {
	_, err := q.db.ExecContext(ctx, upsertPrimaryAgents,
		arg.Backend,
		arg.ProjectDir,
		arg.GitRemote,
		arg.PrimaryAgentsJson,
		arg.UpdatedAt,
	)
	return err
}

const upsertSession = `-- name: UpsertSession :exec
INSERT INTO sessions (
    id, external_id, backend, status, visibility, follow_up,
    project_dir, git_remote, worktree_branch, prompt, title,
    ticket_id, agent, draft, created_at, updated_at, last_read_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    external_id     = excluded.external_id,
    backend         = excluded.backend,
    status          = excluded.status,
    visibility      = excluded.visibility,
    follow_up       = excluded.follow_up,
    project_dir     = excluded.project_dir,
    git_remote      = excluded.git_remote,
    worktree_branch = excluded.worktree_branch,
    prompt          = excluded.prompt,
    title           = excluded.title,
    ticket_id       = excluded.ticket_id,
    agent           = excluded.agent,
    draft           = excluded.draft,
    updated_at      = excluded.updated_at,
    last_read_at    = excluded.last_read_at
`

type UpsertSessionParams struct {
	ID             string
	ExternalID     string
	Backend        string
	Status         string
	Visibility     string
	FollowUp       int64
	ProjectDir     string
	GitRemote      string
	WorktreeBranch string
	Prompt         string
	Title          string
	TicketID       string
	Agent          string
	Draft          string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	LastReadAt     sql.NullTime
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSession,
		arg.ID,
		arg.ExternalID,
		arg.Backend,
		arg.Status,
		arg.Visibility,
		arg.FollowUp,
		arg.ProjectDir,
		arg.GitRemote,
		arg.WorktreeBranch,
		arg.Prompt,
		arg.Title,
		arg.TicketID,
		arg.Agent,
		arg.Draft,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastReadAt,
	)
	return err
}
