// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package sqlitedb

import (
	"context"
	"time"
)

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices
WHERE user_id = ? AND push_token = ?
`

type DeleteDeviceParams struct {
	UserID    string
	PushToken string
}

func (q *Queries) DeleteDevice(ctx context.Context, arg DeleteDeviceParams) error {
	_, err := q.db.ExecContext(ctx, deleteDevice, arg.UserID, arg.PushToken)
	return err
}

const deleteDeviceByPushToken = `-- name: DeleteDeviceByPushToken :exec
DELETE FROM devices
WHERE push_token = ?
`

// Used by the dispatcher when Expo returns DeviceNotRegistered for a
// token; the user_id is irrelevant, the token itself is dead.
func (q *Queries) DeleteDeviceByPushToken(ctx context.Context, pushToken string) error {
	_, err := q.db.ExecContext(ctx, deleteDeviceByPushToken, pushToken)
	return err
}

const listDevicesByUser = `-- name: ListDevicesByUser :many
SELECT user_id, push_token, platform, created_at, last_seen_at FROM devices
WHERE user_id = ?
ORDER BY last_seen_at DESC
`

func (q *Queries) ListDevicesByUser(ctx context.Context, userID string) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevicesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.UserID,
			&i.PushToken,
			&i.Platform,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDevice = `-- name: UpsertDevice :exec
INSERT INTO devices (user_id, push_token, platform, created_at, last_seen_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (user_id, push_token) DO UPDATE SET
    platform     = excluded.platform,
    last_seen_at = excluded.last_seen_at
`

type UpsertDeviceParams struct {
	UserID     string
	PushToken  string
	Platform   string
	CreatedAt  time.Time
	LastSeenAt time.Time
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) error {
	_, err := q.db.ExecContext(ctx, upsertDevice,
		arg.UserID,
		arg.PushToken,
		arg.Platform,
		arg.CreatedAt,
		arg.LastSeenAt,
	)
	return err
}
