// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hosts.sql

package sqlitedb

import (
	"context"
	"time"
)

const deleteHostByID = `-- name: DeleteHostByID :exec
DELETE FROM hosts WHERE id = ?
`

func (q *Queries) DeleteHostByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteHostByID, id)
	return err
}

const deleteHostByUser = `-- name: DeleteHostByUser :exec
DELETE FROM hosts WHERE user_id = ? AND provider = ?
`

type DeleteHostByUserParams struct {
	UserID   string
	Provider string
}

func (q *Queries) DeleteHostByUser(ctx context.Context, arg DeleteHostByUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteHostByUser, arg.UserID, arg.Provider)
	return err
}

const getHostByID = `-- name: GetHostByID :one
SELECT id, user_id, provider, external_id, hostname, status, last_url, last_token, auth_token, auto_wake, created_at, updated_at FROM hosts
WHERE id = ?
`

func (q *Queries) GetHostByID(ctx context.Context, id string) (Host, error) {
	row := q.db.QueryRowContext(ctx, getHostByID, id)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ExternalID,
		&i.Hostname,
		&i.Status,
		&i.LastUrl,
		&i.LastToken,
		&i.AuthToken,
		&i.AutoWake,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHostByUser = `-- name: GetHostByUser :one
SELECT id, user_id, provider, external_id, hostname, status, last_url, last_token, auth_token, auto_wake, created_at, updated_at FROM hosts
WHERE user_id = ? AND provider = ?
`

type GetHostByUserParams struct {
	UserID   string
	Provider string
}

func (q *Queries) GetHostByUser(ctx context.Context, arg GetHostByUserParams) (Host, error) {
	row := q.db.QueryRowContext(ctx, getHostByUser, arg.UserID, arg.Provider)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ExternalID,
		&i.Hostname,
		&i.Status,
		&i.LastUrl,
		&i.LastToken,
		&i.AuthToken,
		&i.AutoWake,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertHost = `-- name: UpsertHost :exec
INSERT INTO hosts (
    id, user_id, provider, external_id, hostname, status,
    last_url, last_token, auth_token, auto_wake, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (user_id, provider) DO UPDATE SET
    external_id = excluded.external_id,
    hostname    = excluded.hostname,
    status      = excluded.status,
    last_url    = excluded.last_url,
    last_token  = excluded.last_token,
    auth_token   = excluded.auth_token,
    auto_wake   = excluded.auto_wake,
    updated_at  = excluded.updated_at
`

type UpsertHostParams struct {
	ID         string
	UserID     string
	Provider   string
	ExternalID string
	Hostname   string
	Status     string
	LastUrl    string
	LastToken  string
	AuthToken  string
	AutoWake   int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) UpsertHost(ctx context.Context, arg UpsertHostParams) error {
	_, err := q.db.ExecContext(ctx, upsertHost,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ExternalID,
		arg.Hostname,
		arg.Status,
		arg.LastUrl,
		arg.LastToken,
		arg.AuthToken,
		arg.AutoWake,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
