// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitedb

import (
	"time"
)

type Host struct {
	ID         string
	UserID     string
	Provider   string
	ExternalID string
	Hostname   string
	Status     string
	LastUrl    string
	LastToken  string
	AuthToken  string
	AutoWake   int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
