// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitedb

import (
	"time"
)

type Device struct {
	UserID     string
	PushToken  string
	Platform   string
	CreatedAt  time.Time
	LastSeenAt time.Time
}

type Host struct {
	ID            string
	UserID        string
	Provider      string
	ExternalID    string
	Hostname      string
	Status        string
	LastUrl       string
	LastToken     string
	AuthToken     string
	NotifierToken string
	AutoWake      int64
	ProviderMeta  string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
