// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitedb

import (
	"context"
)

type Querier interface {
	DeleteDevice(ctx context.Context, arg DeleteDeviceParams) error
	// Used by the dispatcher when Expo returns DeviceNotRegistered for a
	// token; the user_id is irrelevant, the token itself is dead.
	DeleteDeviceByPushToken(ctx context.Context, pushToken string) error
	DeleteHostByID(ctx context.Context, id string) error
	DeleteHostByUser(ctx context.Context, arg DeleteHostByUserParams) error
	GetHostByID(ctx context.Context, id string) (Host, error)
	GetHostByNotifierToken(ctx context.Context, notifierToken string) (Host, error)
	GetHostByUser(ctx context.Context, arg GetHostByUserParams) (Host, error)
	ListDevicesByUser(ctx context.Context, userID string) ([]Device, error)
	UpsertDevice(ctx context.Context, arg UpsertDeviceParams) error
	UpsertHost(ctx context.Context, arg UpsertHostParams) error
}

var _ Querier = (*Queries)(nil)
