// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitedb

import (
	"context"
)

type Querier interface {
	DeleteHostByID(ctx context.Context, id string) error
	DeleteHostByUser(ctx context.Context, arg DeleteHostByUserParams) error
	GetHostByID(ctx context.Context, id string) (Host, error)
	GetHostByUser(ctx context.Context, arg GetHostByUserParams) (Host, error)
	UpsertHost(ctx context.Context, arg UpsertHostParams) error
}

var _ Querier = (*Queries)(nil)
