// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: worktrees.sql

package sqlitedb

import (
	"context"
	"database/sql"
	"time"
)

const deleteWorktree = `-- name: DeleteWorktree :exec
DELETE FROM worktrees WHERE id = ?
`

func (q *Queries) DeleteWorktree(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWorktree, id)
	return err
}

const getCheckpointByID = `-- name: GetCheckpointByID :one
SELECT id, worktree_id, head_commit, head_ref, index_tree, worktree_tree, incremental_commit, created_at, created_by, uploaded_at FROM checkpoints
WHERE id = ?
`

func (q *Queries) GetCheckpointByID(ctx context.Context, id string) (Checkpoint, error) {
	row := q.db.QueryRowContext(ctx, getCheckpointByID, id)
	var i Checkpoint
	err := row.Scan(
		&i.ID,
		&i.WorktreeID,
		&i.HeadCommit,
		&i.HeadRef,
		&i.IndexTree,
		&i.WorktreeTree,
		&i.IncrementalCommit,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UploadedAt,
	)
	return i, err
}

const getWorktreeByID = `-- name: GetWorktreeByID :one
SELECT id, user_id, display_name, owner_kind, owner_id, latest_synced_checkpoint, created_at, updated_at FROM worktrees
WHERE id = ?
`

func (q *Queries) GetWorktreeByID(ctx context.Context, id string) (Worktree, error) {
	row := q.db.QueryRowContext(ctx, getWorktreeByID, id)
	var i Worktree
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.OwnerKind,
		&i.OwnerID,
		&i.LatestSyncedCheckpoint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCheckpoint = `-- name: InsertCheckpoint :exec
INSERT INTO checkpoints (
    id, worktree_id, head_commit, head_ref,
    index_tree, worktree_tree, incremental_commit,
    created_at, created_by
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertCheckpointParams struct {
	ID                string
	WorktreeID        string
	HeadCommit        string
	HeadRef           string
	IndexTree         string
	WorktreeTree      string
	IncrementalCommit string
	CreatedAt         time.Time
	CreatedBy         string
}

func (q *Queries) InsertCheckpoint(ctx context.Context, arg InsertCheckpointParams) error {
	_, err := q.db.ExecContext(ctx, insertCheckpoint,
		arg.ID,
		arg.WorktreeID,
		arg.HeadCommit,
		arg.HeadRef,
		arg.IndexTree,
		arg.WorktreeTree,
		arg.IncrementalCommit,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}

const insertWorktree = `-- name: InsertWorktree :exec
INSERT INTO worktrees (
    id, user_id, display_name, owner_kind, owner_id,
    latest_synced_checkpoint, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertWorktreeParams struct {
	ID                     string
	UserID                 string
	DisplayName            string
	OwnerKind              string
	OwnerID                string
	LatestSyncedCheckpoint string
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

func (q *Queries) InsertWorktree(ctx context.Context, arg InsertWorktreeParams) error {
	_, err := q.db.ExecContext(ctx, insertWorktree,
		arg.ID,
		arg.UserID,
		arg.DisplayName,
		arg.OwnerKind,
		arg.OwnerID,
		arg.LatestSyncedCheckpoint,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listCheckpointsByWorktree = `-- name: ListCheckpointsByWorktree :many
SELECT id, worktree_id, head_commit, head_ref, index_tree, worktree_tree, incremental_commit, created_at, created_by, uploaded_at FROM checkpoints
WHERE worktree_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListCheckpointsByWorktreeParams struct {
	WorktreeID string
	Limit      int64
}

func (q *Queries) ListCheckpointsByWorktree(ctx context.Context, arg ListCheckpointsByWorktreeParams) ([]Checkpoint, error) {
	rows, err := q.db.QueryContext(ctx, listCheckpointsByWorktree, arg.WorktreeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Checkpoint
	for rows.Next() {
		var i Checkpoint
		if err := rows.Scan(
			&i.ID,
			&i.WorktreeID,
			&i.HeadCommit,
			&i.HeadRef,
			&i.IndexTree,
			&i.WorktreeTree,
			&i.IncrementalCommit,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorktreesByOwner = `-- name: ListWorktreesByOwner :many
SELECT id, user_id, display_name, owner_kind, owner_id, latest_synced_checkpoint, created_at, updated_at FROM worktrees
WHERE owner_kind = ? AND owner_id = ?
ORDER BY updated_at DESC
`

type ListWorktreesByOwnerParams struct {
	OwnerKind string
	OwnerID   string
}

func (q *Queries) ListWorktreesByOwner(ctx context.Context, arg ListWorktreesByOwnerParams) ([]Worktree, error) {
	rows, err := q.db.QueryContext(ctx, listWorktreesByOwner, arg.OwnerKind, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Worktree
	for rows.Next() {
		var i Worktree
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.OwnerKind,
			&i.OwnerID,
			&i.LatestSyncedCheckpoint,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorktreesByUser = `-- name: ListWorktreesByUser :many
SELECT id, user_id, display_name, owner_kind, owner_id, latest_synced_checkpoint, created_at, updated_at FROM worktrees
WHERE user_id = ?
ORDER BY updated_at DESC
`

func (q *Queries) ListWorktreesByUser(ctx context.Context, userID string) ([]Worktree, error) {
	rows, err := q.db.QueryContext(ctx, listWorktreesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Worktree
	for rows.Next() {
		var i Worktree
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.OwnerKind,
			&i.OwnerID,
			&i.LatestSyncedCheckpoint,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCheckpointUploaded = `-- name: MarkCheckpointUploaded :exec
UPDATE checkpoints
SET uploaded_at = ?
WHERE id = ?
`

type MarkCheckpointUploadedParams struct {
	UploadedAt sql.NullTime
	ID         string
}

func (q *Queries) MarkCheckpointUploaded(ctx context.Context, arg MarkCheckpointUploadedParams) error {
	_, err := q.db.ExecContext(ctx, markCheckpointUploaded, arg.UploadedAt, arg.ID)
	return err
}

const updateWorktreeOwner = `-- name: UpdateWorktreeOwner :execrows
UPDATE worktrees
SET owner_kind = ?, owner_id = ?, updated_at = ?
WHERE id = ? AND owner_kind = ? AND owner_id = ?
`

type UpdateWorktreeOwnerParams struct {
	OwnerKind   string
	OwnerID     string
	UpdatedAt   time.Time
	ID          string
	OwnerKind_2 string
	OwnerID_2   string
}

// Atomic ownership transfer: only succeeds when the requester knows
// the full current (owner_kind, owner_id) tuple. Both are matched so
// a stale or cross-kind transfer cannot mutate the row even if the
// two kinds reuse the same id namespace by accident.
func (q *Queries) UpdateWorktreeOwner(ctx context.Context, arg UpdateWorktreeOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateWorktreeOwner,
		arg.OwnerKind,
		arg.OwnerID,
		arg.UpdatedAt,
		arg.ID,
		arg.OwnerKind_2,
		arg.OwnerID_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateWorktreePointer = `-- name: UpdateWorktreePointer :exec
UPDATE worktrees
SET latest_synced_checkpoint = ?, updated_at = ?
WHERE id = ?
`

type UpdateWorktreePointerParams struct {
	LatestSyncedCheckpoint string
	UpdatedAt              time.Time
	ID                     string
}

func (q *Queries) UpdateWorktreePointer(ctx context.Context, arg UpdateWorktreePointerParams) error {
	_, err := q.db.ExecContext(ctx, updateWorktreePointer, arg.LatestSyncedCheckpoint, arg.UpdatedAt, arg.ID)
	return err
}
