// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: worktrees.sql

package sqlitedb

import (
	"context"
	"database/sql"
	"time"
)

const deleteCheckpointsByWorktree = `-- name: DeleteCheckpointsByWorktree :exec
DELETE FROM checkpoints WHERE worktree_id = ?
`

// checkpoints has no FK back to worktrees(id), so a worktree delete must
// clear its checkpoint rows explicitly to avoid orphans (see DeleteWorktree).
func (q *Queries) DeleteCheckpointsByWorktree(ctx context.Context, worktreeID string) error {
	_, err := q.db.ExecContext(ctx, deleteCheckpointsByWorktree, worktreeID)
	return err
}

const deleteWorktree = `-- name: DeleteWorktree :exec
DELETE FROM worktrees WHERE id = ?
`

func (q *Queries) DeleteWorktree(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWorktree, id)
	return err
}

const getCheckpointByID = `-- name: GetCheckpointByID :one
SELECT id, worktree_id, head_commit, head_ref, index_tree, worktree_tree, incremental_commit, created_at, created_by, uploaded_at FROM checkpoints
WHERE id = ?
`

func (q *Queries) GetCheckpointByID(ctx context.Context, id string) (Checkpoint, error) {
	row := q.db.QueryRowContext(ctx, getCheckpointByID, id)
	var i Checkpoint
	err := row.Scan(
		&i.ID,
		&i.WorktreeID,
		&i.HeadCommit,
		&i.HeadRef,
		&i.IndexTree,
		&i.WorktreeTree,
		&i.IncrementalCommit,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UploadedAt,
	)
	return i, err
}

const getHeadBundle = `-- name: GetHeadBundle :one
SELECT user_id, tip_sha, base_sha, blob_key, created_at FROM head_bundles
WHERE user_id = ? AND tip_sha = ?
`

type GetHeadBundleParams struct {
	UserID string
	TipSha string
}

func (q *Queries) GetHeadBundle(ctx context.Context, arg GetHeadBundleParams) (HeadBundle, error) {
	row := q.db.QueryRowContext(ctx, getHeadBundle, arg.UserID, arg.TipSha)
	var i HeadBundle
	err := row.Scan(
		&i.UserID,
		&i.TipSha,
		&i.BaseSha,
		&i.BlobKey,
		&i.CreatedAt,
	)
	return i, err
}

const getWorktreeByID = `-- name: GetWorktreeByID :one
SELECT id, user_id, display_name, origin_repo, latest_synced_checkpoint, materialized_checkpoint_id, sync_state, sync_conflict_local_head, sync_conflict_remote_head, sessions_synced_hash, created_at, updated_at FROM worktrees
WHERE id = ?
`

func (q *Queries) GetWorktreeByID(ctx context.Context, id string) (Worktree, error) {
	row := q.db.QueryRowContext(ctx, getWorktreeByID, id)
	var i Worktree
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.OriginRepo,
		&i.LatestSyncedCheckpoint,
		&i.MaterializedCheckpointID,
		&i.SyncState,
		&i.SyncConflictLocalHead,
		&i.SyncConflictRemoteHead,
		&i.SessionsSyncedHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCheckpoint = `-- name: InsertCheckpoint :exec
INSERT INTO checkpoints (
    id, worktree_id, head_commit, head_ref,
    index_tree, worktree_tree, incremental_commit,
    created_at, created_by
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertCheckpointParams struct {
	ID                string
	WorktreeID        string
	HeadCommit        string
	HeadRef           string
	IndexTree         string
	WorktreeTree      string
	IncrementalCommit string
	CreatedAt         time.Time
	CreatedBy         string
}

func (q *Queries) InsertCheckpoint(ctx context.Context, arg InsertCheckpointParams) error {
	_, err := q.db.ExecContext(ctx, insertCheckpoint,
		arg.ID,
		arg.WorktreeID,
		arg.HeadCommit,
		arg.HeadRef,
		arg.IndexTree,
		arg.WorktreeTree,
		arg.IncrementalCommit,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}

const insertHeadBundle = `-- name: InsertHeadBundle :exec
INSERT OR IGNORE INTO head_bundles (
    user_id, tip_sha, base_sha, blob_key, created_at
) VALUES (?, ?, ?, ?, ?)
`

type InsertHeadBundleParams struct {
	UserID    string
	TipSha    string
	BaseSha   string
	BlobKey   string
	CreatedAt time.Time
}

// Idempotent: a tip's first stored bundle wins, so re-pushing a HEAD the
// server already has (already_stored) keeps the original base_sha link.
func (q *Queries) InsertHeadBundle(ctx context.Context, arg InsertHeadBundleParams) error {
	_, err := q.db.ExecContext(ctx, insertHeadBundle,
		arg.UserID,
		arg.TipSha,
		arg.BaseSha,
		arg.BlobKey,
		arg.CreatedAt,
	)
	return err
}

const insertWorktree = `-- name: InsertWorktree :exec
INSERT INTO worktrees (
    id, user_id, display_name, origin_repo,
    latest_synced_checkpoint, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertWorktreeParams struct {
	ID                     string
	UserID                 string
	DisplayName            string
	OriginRepo             string
	LatestSyncedCheckpoint string
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

func (q *Queries) InsertWorktree(ctx context.Context, arg InsertWorktreeParams) error {
	_, err := q.db.ExecContext(ctx, insertWorktree,
		arg.ID,
		arg.UserID,
		arg.DisplayName,
		arg.OriginRepo,
		arg.LatestSyncedCheckpoint,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listCheckpointsByWorktree = `-- name: ListCheckpointsByWorktree :many
SELECT id, worktree_id, head_commit, head_ref, index_tree, worktree_tree, incremental_commit, created_at, created_by, uploaded_at FROM checkpoints
WHERE worktree_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListCheckpointsByWorktreeParams struct {
	WorktreeID string
	Limit      int64
}

func (q *Queries) ListCheckpointsByWorktree(ctx context.Context, arg ListCheckpointsByWorktreeParams) ([]Checkpoint, error) {
	rows, err := q.db.QueryContext(ctx, listCheckpointsByWorktree, arg.WorktreeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Checkpoint
	for rows.Next() {
		var i Checkpoint
		if err := rows.Scan(
			&i.ID,
			&i.WorktreeID,
			&i.HeadCommit,
			&i.HeadRef,
			&i.IndexTree,
			&i.WorktreeTree,
			&i.IncrementalCommit,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorktreesByUser = `-- name: ListWorktreesByUser :many
SELECT id, user_id, display_name, origin_repo, latest_synced_checkpoint, materialized_checkpoint_id, sync_state, sync_conflict_local_head, sync_conflict_remote_head, sessions_synced_hash, created_at, updated_at FROM worktrees
WHERE user_id = ?
ORDER BY updated_at DESC
`

func (q *Queries) ListWorktreesByUser(ctx context.Context, userID string) ([]Worktree, error) {
	rows, err := q.db.QueryContext(ctx, listWorktreesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Worktree
	for rows.Next() {
		var i Worktree
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.OriginRepo,
			&i.LatestSyncedCheckpoint,
			&i.MaterializedCheckpointID,
			&i.SyncState,
			&i.SyncConflictLocalHead,
			&i.SyncConflictRemoteHead,
			&i.SessionsSyncedHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCheckpointUploaded = `-- name: MarkCheckpointUploaded :exec
UPDATE checkpoints
SET uploaded_at = ?
WHERE id = ?
`

type MarkCheckpointUploadedParams struct {
	UploadedAt sql.NullTime
	ID         string
}

func (q *Queries) MarkCheckpointUploaded(ctx context.Context, arg MarkCheckpointUploadedParams) error {
	_, err := q.db.ExecContext(ctx, markCheckpointUploaded, arg.UploadedAt, arg.ID)
	return err
}

const updateWorktreeMaterialization = `-- name: UpdateWorktreeMaterialization :exec
UPDATE worktrees
SET materialized_checkpoint_id = ?, sync_state = ?,
    sync_conflict_local_head = ?, sync_conflict_remote_head = ?,
    sessions_synced_hash = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateWorktreeMaterializationParams struct {
	MaterializedCheckpointID string
	SyncState                string
	SyncConflictLocalHead    string
	SyncConflictRemoteHead   string
	SessionsSyncedHash       string
	UpdatedAt                time.Time
	ID                       string
}

func (q *Queries) UpdateWorktreeMaterialization(ctx context.Context, arg UpdateWorktreeMaterializationParams) error {
	_, err := q.db.ExecContext(ctx, updateWorktreeMaterialization,
		arg.MaterializedCheckpointID,
		arg.SyncState,
		arg.SyncConflictLocalHead,
		arg.SyncConflictRemoteHead,
		arg.SessionsSyncedHash,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateWorktreePointer = `-- name: UpdateWorktreePointer :exec
UPDATE worktrees
SET latest_synced_checkpoint = ?, updated_at = ?
WHERE id = ?
`

type UpdateWorktreePointerParams struct {
	LatestSyncedCheckpoint string
	UpdatedAt              time.Time
	ID                     string
}

func (q *Queries) UpdateWorktreePointer(ctx context.Context, arg UpdateWorktreePointerParams) error {
	_, err := q.db.ExecContext(ctx, updateWorktreePointer, arg.LatestSyncedCheckpoint, arg.UpdatedAt, arg.ID)
	return err
}
