package flyio

import _ "embed"

// clankHostBinary is the linux/amd64 clank-host the provisioner pushes
// into a Sprite. Regenerated by `make embed-host` and .gitignored —
// a fresh checkout fails loudly via go:embed rather than shipping a
// stale binary. Embedded (rather than downloaded) so self-hosters
// need no external release infrastructure.
//
//go:embed clank-host-linux-amd64
var clankHostBinary []byte
